In [2]:
import pandas as pd

df=pd.read_csv("sentiment_analysis.csv")
df.head()

,Year,Month,Day,Time of Tweet,text,sentiment,Platform
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook
2,2017,8,18,night,Don't angry me,negative,Facebook
3,2022,6,8,morning,We attend in the class just for listening teac...,negative,Facebook
4,2022,6,8,noon,"Those who want to go, let them go",negative,Instagram

In [3]:
print(df.shape)

(499, 7)

In [ ]:
df["sentiment"].value_counts()
#tells us how many positive ,negative and neutral values are there

sentiment
neutral     199
positive    166
negative    134
Name: count, dtype: int64

In [ ]:
df.isnull().sum()
#checks for the null values

Year             0
Month            0
Day              0
Time of Tweet    0
text             0
sentiment        0
Platform         0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(105)

In [11]:
df["sentiment"].unique()

<StringArray>
['positive', 'negative', 'neutral']
Length: 3, dtype: str

In [ ]:
import re
#re is regular expression
def clean_text(text):
    text = str(text)
    #converting to lowercase
    text = text.lower()
    #remove the unwanted special cases
    text = re.sub(r'[^\w\s]', '',text)
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [13]:
df["clean_text"]=df["text"].apply(clean_text)

In [14]:
df[["text", "clean_text", "sentiment"]].head(10)

,text,clean_text,sentiment
0,What a great day!!! Looks like dream.,what a great day looks like dream,positive
1,"I feel sorry, I miss you here in the sea beach",i feel sorry i miss you here in the sea beach,positive
2,Don't angry me,dont angry me,negative
3,We attend in the class just for listening teac...,we attend in the class just for listening teac...,negative
4,"Those who want to go, let them go",those who want to go let them go,negative
5,"Its night 2 am, feeling neutral",its night 2 am feeling neutral,neutral
6,2 am feedings for the baby are fun when he is ...,2 am feedings for the baby are fun when he is ...,positive
7,Soooo high,soooo high,neutral
8,Both of you,both of you,neutral
9,Today first time I arrive in the boat. Its ama...,today first time i arrive in the boat its amaz...,positive

In [17]:
import nltk
from nltk.tokenize import word_tokenize

df["tokenize"]=df["clean_text"].apply(word_tokenize)

df[["clean_text", "tokenize", "sentiment"]].head(10)

,clean_text,tokenize,sentiment
0,what a great day looks like dream,"[what, a, great, day, looks, like, dream]",positive
1,i feel sorry i miss you here in the sea beach,"[i, feel, sorry, i, miss, you, here, in, the, ...",positive
2,dont angry me,"[dont, angry, me]",negative
3,we attend in the class just for listening teac...,"[we, attend, in, the, class, just, for, listen...",negative
4,those who want to go let them go,"[those, who, want, to, go, let, them, go]",negative
5,its night 2 am feeling neutral,"[its, night, 2, am, feeling, neutral]",neutral
6,2 am feedings for the baby are fun when he is ...,"[2, am, feedings, for, the, baby, are, fun, wh...",positive
7,soooo high,"[soooo, high]",neutral
8,both of you,"[both, of, you]",neutral
9,today first time i arrive in the boat its amaz...,"[today, first, time, i, arrive, in, the, boat,...",positive

In [18]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\chitrashree\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
#Remove stop words
from nltk.corpus import stopwords

stop_words=set(stopwords.words("english"))